### ISSUE TITLE
NuGet package has a broken URL

### ISSUE THREAD

**Issue by ygoe** [roji/AsyncRewriter#8]
It points to `http://https//github.com/roji/AsyncRewriter`, as can be seen on the NuGet package page.

**Comment by roji** [comment]
Wow, thanks @dg9ngf, that's the first time anyone takes notice of AsyncRewriter :)

This project is still pretty raw, I was planning a cleanup and a blog post on it soon. Are you thinking of using it in a project of yours?

**Comment by ygoe** [comment]
Actually, I couldn't find out what it's about. ;-) Maybe some description in the README would help.

I was just looking for an Npgsql package and checking the author's "reputation" because I didn't know your name. While browsing your repositories list, that name raised my attention. And the broken link to the project site was easy enough to fix.

**Comment by roji** [comment]
Yeah, I know. I'll have to find the time to document it a little bit.

In a nutshell it uses Roslyn to take regular functions and produce asynchronous versions of them. I use them in Npgsql to generate a lot of the async code out of the sync code, this provides a totally separate flow (i.e. the sync and async flows don't depend on one another) without creating a double maintenance nightmare...
